server:
  port: 9001

logging:
  file:
    name: search.log

spring:
  application:
    name: elastic-service
  profiles:
    active: production
  elasticsearch:
    rest:
      uris: http://localhost:9200