spring:
  elasticsearch:
    rest:
      uris: http://localhost:9200


javamelody:
  enabled: true
  excluded-datasources: secretSource,topSecretSource
  spring-monitoring-enabled: true
  init-parameters:
    log: true